<script setup lang="ts">
</script>
<template>
    <div class="sticky top-12">1231231232</div>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
    <p>about</p>
</template>