"""add table

Revision ID: 0a6c6a80b727
Revises: 934f6ca3ce64
Create Date: 2024-04-30 16:04:38.976825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a6c6a80b727'
down_revision: Union[str, None] = '934f6ca3ce64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user_register_process',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('finished_register', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_1_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_1_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_2_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_2_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_3_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_3_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_4_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_4_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_verify', postgresql.BIT(length=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.drop_table('auth_user_register_process')
    # ### end Alembic commands ###
