"""dev

Revision ID: 460ee9251587
Revises: 55d5621cc1e9
Create Date: 2024-05-20 23:43:16.796181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460ee9251587'
down_revision: Union[str, None] = '55d5621cc1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_challenges', sa.Column('user', sa.String(), nullable=True))
    op.create_index(op.f('ix_auth_challenges_user'), 'auth_challenges', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_challenges_user'), table_name='auth_challenges')
    op.drop_column('auth_challenges', 'user')
    # ### end Alembic commands ###
