"""dev

Revision ID: cf102c392675
Revises: 02c79bd0f821
Create Date: 2024-05-16 14:33:55.461411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf102c392675'
down_revision: Union[str, None] = '02c79bd0f821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_passkeys', sa.Column('user_secret', sa.String(), nullable=True))
    op.add_column('auth_passkeys', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('auth_passkeys', sa.Column('deleted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_passkeys', 'deleted_by')
    op.drop_column('auth_passkeys', 'is_deleted')
    op.drop_column('auth_passkeys', 'user_secret')
    # ### end Alembic commands ###
