"""dev

Revision ID: dd7db6634529
Revises: 
Create Date: 2024-05-19 01:25:45.766408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd7db6634529'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_passkeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('raw_id', sa.String(), nullable=False),
    sa.Column('credential_id', postgresql.BYTEA(), nullable=False),
    sa.Column('public_key', postgresql.BYTEA(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('annotate', sa.String(), nullable=True),
    sa.Column('backed_up', sa.Boolean(), nullable=True),
    sa.Column('transports', sa.String(), nullable=True),
    sa.Column('registed_user_agent', sa.String(), nullable=True),
    sa.Column('user_secret', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_index(op.f('ix_auth_passkeys_raw_id'), 'auth_passkeys', ['raw_id'], unique=True)
    op.create_index(op.f('ix_auth_passkeys_user'), 'auth_passkeys', ['user'], unique=False)
    op.create_table('auth_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('operation_log_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_permissions_operation_log_id'), 'auth_permissions', ['operation_log_id'], unique=False)
    op.create_index(op.f('ix_auth_permissions_permission'), 'auth_permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_auth_permissions_user'), 'auth_permissions', ['user'], unique=False)
    op.create_table('auth_registration_attempts',
    sa.Column('challenge', postgresql.BYTEA(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('access_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('challenge')
    )
    op.create_index(op.f('ix_auth_registration_attempts_user'), 'auth_registration_attempts', ['user'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('related_passkey', sa.UUID(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_user'), 'auth_sessions', ['user'], unique=False)
    op.create_table('fedi_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('description_in_markdown', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('avatar_file_content', sa.String(), nullable=True),
    sa.Column('avatar_file_type', sa.String(), nullable=True),
    sa.Column('avatar_file_size', sa.BigInteger(), nullable=True),
    sa.Column('avatar_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('header_file_content', sa.String(), nullable=True),
    sa.Column('header_file_type', sa.String(), nullable=True),
    sa.Column('header_file_size', sa.BigInteger(), nullable=True),
    sa.Column('header_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('last_webfingered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inbox_url', sa.String(), nullable=True),
    sa.Column('outbox_url', sa.String(), nullable=True),
    sa.Column('shared_inbox_url', sa.String(), nullable=True),
    sa.Column('followers_url', sa.String(), nullable=True),
    sa.Column('memorial', sa.Boolean(), nullable=True),
    sa.Column('moved_to_account_id', sa.BigInteger(), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('discoverable', sa.Boolean(), nullable=True),
    sa.Column('also_known_as', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('silenced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hide_collections', sa.Boolean(), nullable=True),
    sa.Column('devices_url', sa.String(), nullable=True),
    sa.Column('sensitized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trendable', sa.Boolean(), nullable=True),
    sa.Column('indexable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fedi_accounts_actor_type'), 'fedi_accounts', ['actor_type'], unique=False)
    op.create_index(op.f('ix_fedi_accounts_description'), 'fedi_accounts', ['description'], unique=False)
    op.create_index(op.f('ix_fedi_accounts_display_name'), 'fedi_accounts', ['display_name'], unique=False)
    op.create_index(op.f('ix_fedi_accounts_domain'), 'fedi_accounts', ['domain'], unique=False)
    op.create_index(op.f('ix_fedi_accounts_uri'), 'fedi_accounts', ['uri'], unique=False)
    op.create_index(op.f('ix_fedi_accounts_url'), 'fedi_accounts', ['url'], unique=False)
    op.create_index(op.f('ix_fedi_accounts_username'), 'fedi_accounts', ['username'], unique=False)
    op.create_table('log_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('error_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_exceptions_error_message'), 'log_exceptions', ['error_message'], unique=False)
    op.create_index(op.f('ix_log_exceptions_error_type'), 'log_exceptions', ['error_type'], unique=False)
    op.create_index(op.f('ix_log_exceptions_node_id'), 'log_exceptions', ['node_id'], unique=False)
    op.create_table('log_operations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('operation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_session', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('operation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_operations_module'), 'log_operations', ['module'], unique=False)
    op.create_index(op.f('ix_log_operations_operation'), 'log_operations', ['operation'], unique=False)
    op.create_index(op.f('ix_log_operations_operation_time'), 'log_operations', ['operation_time'], unique=False)
    op.create_index(op.f('ix_log_operations_related_session'), 'log_operations', ['related_session'], unique=False)
    op.create_index(op.f('ix_log_operations_user'), 'log_operations', ['user'], unique=False)
    op.create_table('mossy_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('fedi_account_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('supported_languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('registration_source', sa.String(), nullable=True),
    sa.Column('recovery_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_mossy_users_fedi_account_id'), 'mossy_users', ['fedi_account_id'], unique=True)
    op.create_table('node_info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('node_type', sa.Enum('fastapi', 'backgrounder', 'scheduler', name='nodetype'), nullable=True),
    sa.Column('cpus', sa.Integer(), nullable=True),
    sa.Column('mem_in_gb', sa.Float(), nullable=True),
    sa.Column('node_name', sa.String(), nullable=True),
    sa.Column('ipv4', sa.String(), nullable=True),
    sa.Column('ipv6', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'node_type', name='uq_node_type')
    )
    op.create_index(op.f('ix_node_info_node_id'), 'node_info', ['node_id'], unique=False)
    op.create_table('oauth_access_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('oauth_apps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('oauth_authorization_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'key', name='uq_user_key')
    )
    op.create_index(op.f('ix_user_config_key'), 'user_config', ['key'], unique=False)
    op.create_index(op.f('ix_user_config_user'), 'user_config', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_config_user'), table_name='user_config')
    op.drop_index(op.f('ix_user_config_key'), table_name='user_config')
    op.drop_table('user_config')
    op.drop_table('system_config')
    op.drop_table('rules')
    op.drop_table('oauth_authorization_codes')
    op.drop_table('oauth_apps')
    op.drop_table('oauth_access_tokens')
    op.drop_index(op.f('ix_node_info_node_id'), table_name='node_info')
    op.drop_table('node_info')
    op.drop_index(op.f('ix_mossy_users_fedi_account_id'), table_name='mossy_users')
    op.drop_table('mossy_users')
    op.drop_index(op.f('ix_log_operations_user'), table_name='log_operations')
    op.drop_index(op.f('ix_log_operations_related_session'), table_name='log_operations')
    op.drop_index(op.f('ix_log_operations_operation_time'), table_name='log_operations')
    op.drop_index(op.f('ix_log_operations_operation'), table_name='log_operations')
    op.drop_index(op.f('ix_log_operations_module'), table_name='log_operations')
    op.drop_table('log_operations')
    op.drop_index(op.f('ix_log_exceptions_node_id'), table_name='log_exceptions')
    op.drop_index(op.f('ix_log_exceptions_error_type'), table_name='log_exceptions')
    op.drop_index(op.f('ix_log_exceptions_error_message'), table_name='log_exceptions')
    op.drop_table('log_exceptions')
    op.drop_index(op.f('ix_fedi_accounts_username'), table_name='fedi_accounts')
    op.drop_index(op.f('ix_fedi_accounts_url'), table_name='fedi_accounts')
    op.drop_index(op.f('ix_fedi_accounts_uri'), table_name='fedi_accounts')
    op.drop_index(op.f('ix_fedi_accounts_domain'), table_name='fedi_accounts')
    op.drop_index(op.f('ix_fedi_accounts_display_name'), table_name='fedi_accounts')
    op.drop_index(op.f('ix_fedi_accounts_description'), table_name='fedi_accounts')
    op.drop_index(op.f('ix_fedi_accounts_actor_type'), table_name='fedi_accounts')
    op.drop_table('fedi_accounts')
    op.drop_index(op.f('ix_auth_sessions_user'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_auth_registration_attempts_user'), table_name='auth_registration_attempts')
    op.drop_table('auth_registration_attempts')
    op.drop_index(op.f('ix_auth_permissions_user'), table_name='auth_permissions')
    op.drop_index(op.f('ix_auth_permissions_permission'), table_name='auth_permissions')
    op.drop_index(op.f('ix_auth_permissions_operation_log_id'), table_name='auth_permissions')
    op.drop_table('auth_permissions')
    op.drop_index(op.f('ix_auth_passkeys_user'), table_name='auth_passkeys')
    op.drop_index(op.f('ix_auth_passkeys_raw_id'), table_name='auth_passkeys')
    op.drop_table('auth_passkeys')
    # ### end Alembic commands ###
